data_ingestion_config:
  dataset_download_url: 
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data

data_transformation_config:
  
  transformed_dir: transformed_dat

prediction_config:
  dataset_download_url: 
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: data_prediction
  predicted_dir: predicted_data